### ISSUE TITLE
The library name is a misnomer

### ISSUE THREAD

**Issue by madphysicist** [mourner/quickselect#3]
This is a very neat library/function. I am particularly happy that you chose to implement Floyd-Rivest rather than introselect. As a nitpick, the name quickselect seems like a misnomer considering that it refers to a completely different algorithm.

**Comment by mourner** [comment]
I don't think it's a misnomer — Floyd-Rivest is a [variation of Quickselect](https://en.wikipedia.org/wiki/Quickselect). Glad you like it though :)
