### ISSUE TITLE
Please add a LICENSE.md

### ISSUE THREAD

**Issue by pjcozzi** [mourner/quickselect#5]
Hi @mourner!  We are planning to use this and rbrush in Cesium.  Does this use the same license as rbrush?  Would you be able to add a LICENSE.md file here so we can link to it?

Thanks and hope to see you at the Mapbox conference and FOSS4G NA.

**Comment by mourner** [comment]
Looking forward to rbush/quickselect in Cesium! The license is ISC (it's stated in `package.json`), but let me add an explicit one.

**Comment by pjcozzi** [comment]
Wow, that was fast, thank you! 🏅
