### ISSUE TITLE
quickselect 1.1.0 export change breaks dependees

### ISSUE THREAD

**Issue by MilosRasic** [mourner/quickselect#6]
1.1.0 changed from module.exports to es6 export default. 

This causes dependees that require quickselect as caret dependency in package.json and import it with a require(), like https://github.com/mourner/rbush, to import an object and fail when trying to call it as a function.

The resulting error with console.log() of quickselect from rbush/index.js
![quickselect](https://user-images.githubusercontent.com/533052/38302497-301d892c-3803-11e8-816f-af6080bd20c7.png)

Interestingly, we use babel-add-module-exports-plugin in build and it's not helping. Either way, the package shouldn't be forcing users to use the plugin. A change in how the module is exported warrants a major version bump.

**Comment by mourner** [comment]
Sorry for the trouble and thanks for the report! 

Quickselect `main` exports itself properly — you can see it here: https://unpkg.com/quickselect@1.1.0/quickselect.js

Looks like your Babel stack is configured in such a way so that when you do `require('quickselect')`, it takes the new exposed `module` and converts it back to CommonJS — I'm not sure why though. The assumption with `quickselect` is that non-ES environments will use the `main` entry point + `require` while ES environments will use `module` entry point with `import`.

**Comment by MilosRasic** [comment]
Yeah, noticed that, but afaik webpack prefers module over main.

According to https://github.com/webpack/webpack/issues/5756, that's the intended behaviour. Not sure if anything changed in webpack 4 since we are still using v3, but I doubt it, since, again afaik, it's needed for module treeshaking.

If anyone else comes here looking for a solution to this problem, the workaround I just got working is to add `"quickselect": "1.0.1",` to your package.json, but since rbush will just make it's own node_modules and install 1.1.0 there and use that, you also need to add a resolve.alias in webpack config to make it always use 1.0.1 regardless of where it is imported:

```
resolve: {
	alias: {
		quickselect: path.resolve('./node_modules/quickselect'),
	},
},
```

**Comment by mourner** [comment]
If this is indeed breaking, let me publish `v1.1.1` with a revert and then `v2.0` exposing a ES module.

**Comment by mourner** [comment]
Published `v1.1.1` removing the `module` field and `v2.0.0` adding it back. Let me know how this works.

**Comment by ahocevar** [comment]
Thanks @mourner, the `v1.1.1` release also fixed https://github.com/openlayers/openlayers/issues/8051.

**Comment by MilosRasic** [comment]
Works in our build as well. Thanks!
