### ISSUE TITLE
Export module version in JavaScript API

### ISSUE THREAD

**Issue by matjon** [mourner/quickselect#7]
Hello,
For GPL compliance, we have to provide source code exactly as used in our program. This can be problematic to determine if quickselect is included in processed source code files.

It would be nice if quickselect provided a version number accessible from JavaScript, such as 

    var quickselectversion = ....

**Comment by mourner** [comment]
Sorry but I'd prefer not to do that. It's an issue with tooling on your side, not something open source authors should be worried about.
